### ISSUE TITLE
Quero mais infomações

### ISSUE THREAD

**Issue by dmop** [luizhenriquesoares/machine-learning-and-artificial-intelligence-articles#2]

**Comment by luizhenriquesoares** [comment]
Saturação do gradiente, ou degradação ? Maquina de Botzman restrita ? auto encoders? modelo de sequenciamento, processamento de audio com long short time memory.

**Comment by dmop** [comment]
kkkk , volta a postar pow, to lendo os textos

**Comment by dmop** [comment]
kkkkkkkkkkkkkkkkkkkkk

**Comment by dmop** [comment]
cade tu bixo

**Comment by luizhenriquesoares** [comment]
meu número antigo já era;

(一一)  九八三六五四六二一

**Comment by dmop** [comment]
kkkk cade teu novo

**Comment by dmop** [comment]
tas na china é?
